### ISSUE TITLE
compatibility with github

### ISSUE THREAD

**Issue by zimbatm** [softprops/git-codeowners#1]
Hi,

git-codeowners looks like the right way to quickly test if files will be managed by github.

Is there any way that we could verify that the tool has the same understanding as github in regards to file matching?

For example I think that github would understand: `foo/bar @owner` to match all the files under `foo/bar` whereas git-codeowners doesn't.

**Comment by softprops** [comment]
I'll take a closer look at this weekend. do you have an example repo I could clone an test with?

**Comment by zimbatm** [comment]
We're using it over at https://github.com/NixOS/nixpkgs . It's a rather large repo.

**Comment by zimbatm** [comment]
Thanks for looking by the way :)

**Comment by softprops** [comment]
I took a look at this and did find some unhandled cases, Ill try to get a new release out soon with improvements

**Comment by softprops** [comment]
`brew upgrade git-codeowners`

This should be fixed now. If you query a file within an owned directory the directory owner should now be resolved


```bash
$ grep python .github/CODEOWNERS
/pkgs/top-level/python-packages.nix     @FRidh
/pkgs/development/interpreters/python   @FRidh
/pkgs/development/python-modules        @FRidh
/doc/languages-frameworks/python.md     @FRidh
$ git codeowners  pkgs/development/interpreters/python/setup-hook.py
@FRidh
```

**Comment by zimbatm** [comment]
thanks!
